// react/myapp/src/App.js
import { useEffect, useRef, useState } from 'react';
import './App.css';
//REPRESENTA UM COMPONENTE DA INTERFACE DO USUARIO E EU AMO A SIMPLICIDADE DISSO
function App() {
  const [todos,setTodos] = useState([]);

  //binding
  const todoText = useRef();

   // Side Effects / Lifecycle
   useEffect(() => {
    const existingTodos = localStorage.getItem('todos');
    setTodos(existingTodos ? JSON.parse(existingTodos) : []);
  }, []);

  //events
  function addTodo(event){
    const next = [...todos, todoText.current.value];
    setTodos(next);
    localStorage.setItem('todos', JSON.stringify(next))
  }
  return (
    <div className="App">
    <ul>
      {todos.map(todo => ( <li key={todo}>{todo}</li>))}
    </ul>
    <form onSubmit={addTodo}>
      <input ref={todoText}></input>
      <input type="submit" value="Add Todo"></input>
    </form>
    </div>
  );
}

export default App;

// SVELT/my-app/src/App.svelte
<script>
	import { onMount } from 'svelte';

	let todos = [];
	let todoText = '';

	onMount(() => {
		const existingTodos = localStorage.getItem('todos');
    	todos = JSON.parse(existingTodos) || [];
	});

	function addTodo() {
		todos = [...todos, todoText];
    	localStorage.setItem('todos', JSON.stringify(todos));
	}

</script>

<main>

	<ul>
		{#each todos as todo}
			<li>{todo}</li>
		{/each}
	</ul>

	<form on:submit|preventDefault={addTodo}>
	
		<input bind:value={todoText} placeholder="What needs to be done?">
		<input type="submit" value="Add todo">
	</form>

</main>
